### ISSUE TITLE
Add support CookieClient

### ISSUE THREAD

**Issue by ihostage** [pac4j/lagom-pac4j#13]

**Comment by leleuj** [comment]
The version 1.0.1 is for bugfix. A new feature must go in version 1.1.0 and if it's a breaking change, we need to create a version 2.0.0. See: http://www.pac4j.org/3.5.x/docs/backward-compatibility.html

**Comment by ihostage** [comment]
Thank you, Jerome! 👍I planned to propose up version `1.1.0` after discussing this issue. But you read my mind 😄
