### ISSUE TITLE
Add support Lagom 1.5

### ISSUE THREAD

**Issue by ihostage** [pac4j/lagom-pac4j#16]

**Comment by ihostage** [comment]
Hello, @leleuj! 
Can you merge #17 and release `2.0.0` version?
Also please create a `lagom-pac4j-demo` repository 😉

**Comment by leleuj** [comment]
Hey, PR merged, release done (should be available in the Maven central repo in a few hours), repo created and announcement done (https://groups.google.com/forum/?fromgroups#!topic/pac4j-announce/TcXwwCo2yo0).

**Comment by ihostage** [comment]
Thanks a lot, Jerome! 👍
