### ISSUE TITLE
Add ability to get JWT token to pass along

### ISSUE THREAD

**Issue by jasoncarreira** [pac4j/lagom-pac4j#23]
If your Lagom service is calling other services it may need to pass along the JWT token as part of the header in those calls. lagom-pac4j should add the ability to get this token and maybe even helper functions to add it to the client. 

Here's a trait I created to get the JWT:
```trait JwtSecuredService extends SecuredService {
  def withJwt[Request, Response](serviceCall: String => ServerServiceCall[Request, Response])
    : ServerServiceCall[Request, Response] = {
    ServerServiceCall.compose { requestHeader =>
      val maybeJwt: Option[String] = requestHeader.getHeader(AUTHORIZATION_HEADER)
      maybeJwt match {
        case Some(jwtString) => serviceCall(jwtString)
        case None => throw Forbidden("No JWT found at " + AUTHORIZATION_HEADER)
      }
    }
  }
}
```

Note that in this case the jwtString includes the "Bearer " part, but that's okay because you need it when you use it in the service call:

```
contactService
              .getContactInfo(userId)
              .handleRequestHeader(rh => rh.addHeader(AUTHORIZATION_HEADER, jwt))
              .invoke(NotUsed)
```

**Comment by ihostage** [comment]
@jasoncarreira you are right! 👍 
We already implement this on our project, but yet not moved this to the library. I will try to do this soon.
