### ISSUE TITLE
lagom-pac4j_2.13 not available on Maven Central

### ISSUE THREAD

**Issue by bc-obou** [pac4j/lagom-pac4j#29]
As used on latest Lagom 1.6 release.

Please, check it on:
[https://search.maven.org/search?q=a:lagom-pac4j*](https://search.maven.org/search?q=a:lagom-pac4j*)

**Comment by ihostage** [comment]
Yes, it's not released until. You can try a SNAPSHOT version https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/lagom-pac4j_2.13/2.0.1-SNAPSHOT/

**Comment by ihostage** [comment]
Hi, Jerome @leleuj! 👋 
Can you release a `v2.1.0`?

**Comment by leleuj** [comment]
Happy new year!
I just cut the 2.1.0 release, it should show up in the Maven central repo within a few hours...

**Comment by bc-obou** [comment]
Many thanks! And Happy New Year!!!
