### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by ihostage** [pac4j/lagom-pac4j#3]

**Comment by leleuj** [comment]
I can handle this one if you want, I'm used to...

**Comment by ihostage** [comment]
That would be great 👍 Mainly, I haven't secret GPG keys to sign pac4j artifacts 😄

**Comment by leleuj** [comment]
@ihostage as promised, I set up the Travis build: https://travis-ci.org/pac4j/lagom-pac4j/builds/448423053

**Comment by ihostage** [comment]
Thank you, @leleuj! 👍
