### ISSUE TITLE
Payload serialization happens before authenticate

### ISSUE THREAD

**Issue by gastonschabasmosaic** [pac4j/lagom-pac4j#37]
Hi there. I'm building a lagom service using `lagom-pac4j` lib and I based my project using this demo https://github.com/pac4j/lagom-pac4j-scala-demo as an example. I could implement the lib and integrate it with an external auth service. It's working fine the authentication and authorization mechanism. So, when the service receive a request with a valid token it returns a 200 and 403 in the other cases. The issue that I'm facing is when the service receive a request with an invalid payload (for example, a json that contains an string where the endpoint is expecting an int in that field) it returns a 400 no matter if the token is valid, invalid or no token was sent in the headers. I guess that what is happening here is that the serialization is being executed before the auth mechanism. Is there a way to return 403 when the payload has an unexpected schema instead of return a 400? Thanks in Advance

Regards
Gastón

**Comment by leleuj** [comment]
Please use the mailing list for questions: http://www.pac4j.org/mailing-lists.html

**Comment by ihostage** [comment]
Hi @gastonschabasmosaic!
This library uses [_Service Call Composition_](https://www.lagomframework.com/documentation/1.6.x/java/ServiceImplementation.html#Service-call-composition) feature of Lagom. And you are right, deserialization of body request executed before auth logic and we can't change it.
