### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by ihostage** [pac4j/lagom-pac4j#4]

**Comment by leleuj** [comment]
I highly recommend to copy/paste this README: https://github.com/pac4j/j2e-pac4j as example...

**Comment by ihostage** [comment]
Thanks, Jerome! 👍

**Comment by leleuj** [comment]
I just gave you the write right on this repo: is it better?

**Comment by ihostage** [comment]
Great! 👍I can create pages now 🎉

**Comment by leleuj** [comment]
I slightly refactored the README and the wiki to follow the latest changes in the other READMEs.

**Comment by ihostage** [comment]
👌 Something else needed? Or you can merge PR https://github.com/pac4j/lagom-pac4j/pull/7?

**Comment by leleuj** [comment]
Nope. I just merged it.

**Comment by ihostage** [comment]
🎉
