### ISSUE TITLE
Support JWT authenticator

### ISSUE THREAD

**Issue by ihostage** [pac4j/lagom-pac4j#6]

**Comment by leleuj** [comment]
I may create a lagom-pac4j-demo repository to host a specific demo for lagom-pac4j if you want...

**Comment by ihostage** [comment]
Thanks, Jerome! I planning to write an example in repository [Lagom Recipes](https://github.com/lagom/lagom-recipes). But if I can't do it, I'll ask you to create `lagom-pac4j-demo` repository. 😉
